# Generated by Django 4.2.6 on 2023-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred_boards',
            field=models.ManyToManyField(blank=True, to='boards.board'),
        ),
    ]
